language: objective-c
xcode_workspace: CleanroomLogger.xcworkspace
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty

script:
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-iOS -configuration Release -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 120 clean build | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-iOS -configuration Release -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 120 test | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-OSX -configuration Release -destination 'platform=macOS' -destination-timeout 120 clean build | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-OSX -configuration Release -destination 'platform=macOS' -destination-timeout 120 test | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-tvOS -configuration Release -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 120 clean build | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-tvOS -configuration Release -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 120 test | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-watchOS -configuration Release -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 120 clean build | xcpretty

