language: objective-c
xcode_workspace: CleanroomLogger.xcworkspace
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

#
# Note: Unit test scripts commented out due to a problem reliably launching the
#       simulator from the command line. See:
#
#       https://github.com/travis-ci/travis-ci/issues/3040
#
# A possible work-around; not yet tested:
#
#       before_install: open -b com.apple.iphonesimulator
#

script:
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' clean test | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-OSX -destination 'platform=macOS' clean test | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' clean test | xcpretty
- set -o pipefail && xcodebuild -workspace CleanroomLogger.xcworkspace -scheme CleanroomLogger-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' clean build | xcpretty
